version: "3.6"

services:

  db:
    container_name: mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - ./utils/mydb/database_init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - "8080:8080"
