version: "3.0"

services:

  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /Users/ik/elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - es-net

  kibana:
    container_name: kb
    image: docker.elastic.co/kibana/kibana:5.2.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - es-net

networks:
  es-net:
    driver: bridge